"""create claims table

Revision ID: 6cf9efc0e59a
Revises: 
Create Date: 2026-03-10 20:05:55.420895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cf9efc0e59a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('patient_name', sa.String(), nullable=True),
    sa.Column('hospital_name', sa.String(), nullable=True),
    sa.Column('total_bill', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_claim_id'), 'claims', ['claim_id'], unique=True)
    op.create_index(op.f('ix_claims_hospital_name'), 'claims', ['hospital_name'], unique=False)
    op.create_index(op.f('ix_claims_id'), 'claims', ['id'], unique=False)
    op.create_index(op.f('ix_claims_patient_name'), 'claims', ['patient_name'], unique=False)
    op.create_index(op.f('ix_claims_status'), 'claims', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claims_status'), table_name='claims')
    op.drop_index(op.f('ix_claims_patient_name'), table_name='claims')
    op.drop_index(op.f('ix_claims_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_hospital_name'), table_name='claims')
    op.drop_index(op.f('ix_claims_claim_id'), table_name='claims')
    op.drop_table('claims')
    # ### end Alembic commands ###
